import case_slider_picture_left_1 from '/src/assets/images/cases-slider-markssite-left-1.png';
import case_slider_picture_right_1 from '/src/assets/images/cases-slider-markssite-right-1.png';
import case_slider_picture_left_2 from '/src/assets/images/cases-slider-markssite-left-2.png';
import case_slider_picture_right_2 from '/src/assets/images/cases-slider-markssite-right-2.png';
import case_slider_picture_left_3 from '/src/assets/images/cases-slider-markssite-left-3.png';
import case_slider_picture_right_3 from '/src/assets/images/cases-slider-markssite-right-3.png';
import case_slider_picture_left_4 from '/src/assets/images/cases-slider-markssite-left-4.png';
import case_slider_picture_right_4 from '/src/assets/images/cases-slider-markssite-right-4.png';
import case_slider_picture_left_5 from '/src/assets/images/cases-slider-markssite-left-5.png';
import case_slider_picture_right_5 from '/src/assets/images/cases-slider-markssite-right-5.png';
import case_slider_picture_left_6 from '/src/assets/images/cases-slider-markssite-left-6.png';
import case_slider_picture_right_6 from '/src/assets/images/cases-slider-markssite-right-6.png';

import case_slider_picture_left_1_2 from '/src/assets/images/cases-slider-markssite-left-1_2.png';
import case_slider_picture_right_1_2 from '/src/assets/images/cases-slider-markssite-right-1_2.png';
import case_slider_picture_left_2_2 from '/src/assets/images/cases-slider-markssite-left-2_2.png';
import case_slider_picture_right_2_2 from '/src/assets/images/cases-slider-markssite-right-2_2.png';
import case_slider_picture_left_3_2 from '/src/assets/images/cases-slider-markssite-left-3_2.png';
import case_slider_picture_right_3_2 from '/src/assets/images/cases-slider-markssite-right-3_2.png';
